name: 'Build packages'
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      - uses: cachix/cachix-action@v12
        with:
          name: welteki
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - name: Build faasd 🔧
        run: |
          nix build -L .#faasd
      - name: Build containerd 🔧
        run: |
          nix build -L .#faasd-containerd
      - name: Build cni-plugin 🔧
        run: |
          nix build -L .#faasd-cni-plugins
      - name: Build OpenFaaS core images 🔧
        run: |
          nix build .#gateway-image \
            .#queue-worker-image \
            .#nats-image \
            .#prometheus-image
